### ISSUE TITLE
No 'Post Status or Note' editor.

### ISSUE THREAD

**Issue by Kathrin84** [synergylearning/moodle-format_socialwall#3] opened 2015-06-15 08:30 UTC
I there, 
I wanted to try your course format and I don't know what I did wrong, but in my Social Wall course, there's no Post Status or Note editor:
![socialwall_probs](https://cloud.githubusercontent.com/assets/4711883/8155924/46aac79a-1349-11e5-8099-47f03bb2d4b5.png)

I put the folder socialwall to course->format.
And I also installed the other plugins in the correct folders. Permissions are also correct.

I installed the plugins within Moodle.

I created a new course (everything is visible) and directly chose the socialwall format.
However it does not work...

Maybe you could guess what I eventually did wrong?

**Comment by awagner** [comment] 2015-06-15 15:02
Hi Kathrin, 

thanks for your feedback. If you have the opportunity to switch in debug mode, please setup the debugging mode as shown here:

![clipboard01](https://cloud.githubusercontent.com/assets/5470564/8162785/cb80759c-137f-11e5-8fbc-6841428de47b.jpg)

Do you get any debugging messages?

For further investigation, can you please tell us:
- your moodle version
- which kind of browser you use
- which editor is configurated in your moodle

Is it possible to make a screenshot, where i can see the area above the (missing) post editor.

Kind regards
Andi

**Comment by Kathrin84** [comment] 2015-06-16 06:43
Hi Andi,

thanks for your response. 
I just get debugging messages for Adobe Connect because it is disabled in our development environment. But your course format throws no messages.

![socialwall_withdebugging](https://cloud.githubusercontent.com/assets/4711883/8177230/f0b6374c-1402-11e5-95f9-0db14f7121b3.png)

Our Moodle version is 2.8.5+.
Behaviour (missing editor) is all the same within the browsers Safari, Chrome and Firefox.
Within Moodle we use Atto as our deafult text editor.

My colleague said that your hint "Do not change an existing site to the Socialwall format. It is possible and will work just fine, but will have undesired results/consequences." would mean that your plugin could not be installed on an existing site, is that correct?

I understood it that way that existing course sites should not be changed to your format.

Best regards
Kathrin

**Comment by awagner** [comment] 2015-06-16 09:51
Hi Kathrin, 

thanks for your response. 

The hint is from Chris (Kenniburg) and my understanding is as follows:

when you change a existings course, which contains activities form topics format to social wall format you will (currently) run into following problem:

The activities placed in topic 1 and above are visible anymore, because (normally) socialwall format only displays topic0 at the top of the courses main page.
To get around this you have to move all the activities into topic0 and then switch to social wall course format, When you want to attach existing activities to a post.

We are working on this for the next version, there will be a activities picker, where you will have the posibillity to select an existing activitiy and attach this to a post.

I don't think that this fact is related to you problem.

Why is topic 0 not shown in your screenshot? Do you have tried to create a new course with standard settings and setup social wall format?

Kind Regards
Andi

**Comment by Kathrin84** [comment] 2015-06-16 10:54
I created a new course with topics format as standard:
![course_topics_format](https://cloud.githubusercontent.com/assets/4711883/8181494/a9caf7ae-1426-11e5-89f8-a3f1598c30b1.png)

Then I switched the format to socialwall:
![course_socialwall_format](https://cloud.githubusercontent.com/assets/4711883/8181509/bd4226f4-1426-11e5-982b-b8126ce65f50.png)

**Comment by ghost** [comment] 2015-07-31 12:50
Hi, I'm having the same issue as Kathrin.
- I've created the course as a social wall course (i.e. it hasn't been converted from any other type).
- I'm using Moodle 2.9.1+ (Build: 20150730).
- I've used both Google Chrome (Version 44.0.2403.125 m) and Internet Explorer 11.
- I'm using the Atto HTML editor.

I enabled debugging, but didn't receive any errors. However, I did see an error when using each browser's developer tools.

I've attached a screenshot:
![no post status or editor](https://cloud.githubusercontent.com/assets/9303042/9007620/ebb69b64-378a-11e5-8a02-953c50b537de.jpg)

Thanks,
Duncan.

**Comment by awagner** [comment] 2015-07-31 12:58
Hi Duncan, hi Kathrin

thanks for reporting this. We are currently working on an update which includes al lot of additional features. We will check compatiblity to Moodle 2.9 at the end (and hopefully) fix this error then.

I would appreciate to get back to you, in the case i could not reproduce the error.

Thank again
Andi

**Comment by awagner** [comment] 2015-09-21 14:45
Hi Duncan, 

i have fixed the error you described (will be in the next release), but i fear that will be not sovling your problem. I have tested on moodle 2.9 (with unfixed error) and the form has shown up anyway.

Can you please give me feedback after the next release (will be coming in Oct),

Thanks
Andi

**Comment by ghost** [comment] 2015-09-21 18:03
Hi,

I'll keep an eye out and let you know the result.

Thanks.

Sent from Yahoo Mail on Android

**Comment by awagner** [comment] 2016-02-01 13:53
Hi everybody, 

we have fixed this really-hard-to-find problem in the lastest release. Thanks a lot for reporting!

Kind regards
Andi

**Closed as completed by awagner** 2016-02-01 13:53 UTC

**Comment by kennibc** [comment] 2016-02-01 13:57
I have seen this happen with a javascript error with a third party block or theme.  The post box doesn't show up.  In the past it was related to a block or theme and I am unsure if this is related.  If possible, I'd try to switch the theme for the course and remove blocks.
